# Spark master
master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    SPARK_PUBLIC_DNS: localhost
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./conf/master/spark-defaults.conf:/conf/spark-defaults.conf
    - ./conf/common/log4j.properties:/conf/log4j.properties
    - ./target:/tmp/target

# Hadoop distributed file system
hadoop:
  build: .
  command: /etc/bootstrap.sh -d
  hostname: hadoop
  ports:
    - 9000:9000
    - 50070:50070
    - 50075:50075

# Spark worker 1
worker1:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker1
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 1
    SPARK_WORKER_MEMORY: 8G
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./conf/worker1/spark-defaults.conf:/conf/spark-defaults.conf
    - ./conf/common/log4j.properties:/conf/log4j.properties

# Spark worker 2
worker2:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker2
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 1
    SPARK_WORKER_MEMORY: 8G
    SPARK_WORKER_PORT: 8882
    SPARK_WORKER_WEBUI_PORT: 8082
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7022
    - 7023
    - 7024
    - 7025
    - 7026
    - 8882
  ports:
    - 8082:8082
  volumes:
    - ./conf/worker2/spark-defaults.conf:/conf/spark-defaults.conf
    - ./conf/common/log4j.properties:/conf/log4j.properties

# Spark worker 3
worker3:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker3
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 1
    SPARK_WORKER_MEMORY: 8G
    SPARK_WORKER_PORT: 8883
    SPARK_WORKER_WEBUI_PORT: 8083
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7032
    - 7033
    - 7034
    - 7035
    - 7036
    - 8883
  ports:
    - 8083:8083
  volumes:
    - ./conf/worker3/spark-defaults.conf:/conf/spark-defaults.conf
    - ./conf/common/log4j.properties:/conf/log4j.properties

# Spark worker 4
worker4:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker4
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 1
    SPARK_WORKER_MEMORY: 8G
    SPARK_WORKER_PORT: 8884
    SPARK_WORKER_WEBUI_PORT: 8084
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7042
    - 7043
    - 7044
    - 7045
    - 7046
    - 8884
  ports:
    - 8084:8084
  volumes:
    - ./conf/worker4/spark-defaults.conf:/conf/spark-defaults.conf
    - ./conf/common/log4j.properties:/conf/log4j.properties
